### ISSUE TITLE
Version out of sync with upstream

### ISSUE THREAD

**Issue by reporter123** [flathub/org.kde.kdiff3#5]
The current release version of kdiff3 is 1.9.6. Flathub is showing 1.9.4.

**Comment by travier** [comment]
This is likely because the URL template in https://github.com/flathub/org.kde.kdiff3/blob/master/org.kde.kdiff3.json#L28 is not correct. See https://github.com/flathub/org.kde.ark/blob/master/org.kde.ark.json#L265 for example.

**Comment by reporter123** [comment]
Seems to be fixed now
